### ISSUE TITLE
GET http://localhost:3000/service-worker.js returns index.html when using npm start

### ISSUE THREAD

**Issue by Ark-kun** [cra-template/pwa#27]
I use `npm start` and I've noticed that when I do HTTP GET for `http://localhost:3000/service-worker.js` the website returns the index.html page with HTML MIME type. Same with `http://localhost:3000/service-worker.ts`.

This causes the SW registration to fail when using `npm start`.

This issue has already been reported several times: https://github.com/facebook/create-react-app/issues/658 https://stackoverflow.com/questions/57175019/how-can-i-enable-service-worker-in-dev-mode-in-create-react-app#comment117197616_57175043

**Comment by jeffposnick** [comment]
That's expected—the idea is that the service worker is only actually served in production.

There is a long history behind when and how the service worker is served in development vs. production in `create-react-app`, and the current approach is what was eventually determined to be the cleanest, with the lowest chance of surprises.

It's entirely possible that you want different behavior, like serving some sort of modified service worker file in the development environment instead of nothing at all. I'd say that using the out of the box `create-react-app` tooling is probably not the best option for that use case, unfortunately.
