### ISSUE TITLE
Error with pwa or pwa-typescript installation

### ISSUE THREAD

**Issue by paolord** [cra-template/pwa#3]
First of all, I'm not sure if this is the right repo to put this.

Running `npx create-react-app . --template pwa-typescript`, installation fails at a statSync error with a missing gitignore file.

Also, after `npx create-react-app . --template pwa` and running `npm start` an error occurs with a missing module `web-vitals` in `./src/reportWebVitals.js`. Manually installing web-vitals with `npm i --save web-vitals` fixed it. 

Sorry I don't have screenshots, npm start command cleared my terminal.

Node version: 12.18.3
npm version: 6.14.6

**Comment by jeffposnick** [comment]
Thanks for pointing that out—we'll get the missing `gitignore` file added in #4.

In general, though, these templates require `create-react-app` v4 or higher, which I don't believe has been released yet.

As soon as it's available, https://create-react-app.dev/docs/making-a-progressive-web-app/ will be updated to refer to these templates and you can give them a shot.

(Arguably we could put something in the README saying "requires `create-react-app` v4 or higher" but that's a little weird since `npx create-react-app` will just run whatever the `latest` release is.)

**Comment by paolord** [comment]
I'm just starting out in PWAs and read the cra docs and some tutorials and expected the default template being pwa ready, but they weren't and it didn't say anything on the docs. I guess I jumped the gun when I read the latest [PR](https://github.com/facebook/create-react-app/pull/9349) on create-react-app, thinking that the pwa-templates were official already.

**Comment by jeffposnick** [comment]
This should be fixed in the `v1.0.2` release of `cra-template-pwa-typescript`.
